### ISSUE TITLE
Improve dark theme 

### ISSUE THREAD

**Issue by daniel-lerch** [skynet-im/skynet-android#14]
1. Usually Skynet shows a text _Type a message..._ in an empty textbox in the `ChatActivity` but this text is not readable using the dark theme.
2. As long as there are no profile images it would look better if the dark theme would use darker colors for generating an image from the initials.
3. It would be nice to have an emoji keyboard fitting to Skynet's or the systems color theme.

**Comment by Twometer** [comment]
The major bugs regarding the dark theme have now been fixed.
