### ISSUE TITLE
Multiple dialog boxes for 'no connection'

### ISSUE THREAD

**Issue by daniel-lerch** [skynet-im/skynet-android#21]
**Describe the bug**
# 🍪+ 👨‍💻 → 😠 #
I don't like to play cookie clicker while trying to debug Skynet.

**To Reproduce**
1. Open the `CreateAccountActivity`
2. Stop the server application
3. A message _Could not reach the Skynet servers..._ appears
4. Wait a few minutes
5. Have fun closing dozens of messages

**Expected behavior**
One dialog with confirmation is enough for me. The second dialog should not appear before I press _Create Account_ again.

**Screenshot**
![Screenshot_20200415-164201](https://user-images.githubusercontent.com/36048059/79366693-ef76be00-7f4c-11ea-9f34-8507eca2283e.png)

**Smartphone**
 - Device: Galaxy S6
 - OS: Android 7.0

**Comment by Twometer** [comment]
Ok, for that description you get a high-priority bugfix 😂😂😂

**Comment by Twometer** [comment]
Can you try again?

**Comment by daniel-lerch** [comment]
Works perfectly now. I never know what to provide as bug description but issues with a joke seem to get fixed must quicker 🤣
