### ISSUE TITLE
Enter to send doesn't work in AVD

### ISSUE THREAD

**Issue by daniel-lerch** [skynet-im/skynet-android#23]
**To Reproduce**
1. Open Skynet in an emulator and login
2. Go to settings and enable 'Enter to send'
3. Open a chat
4. Write a message and press enter
5. Nothing happens

**Expected behavior**
Skynet should send the message when I press Enter instead of doing nothing.

**Smartphone (please complete the following information):**
 - Device: AOSP on IA Emulator (AVD)
 - OS: Android 9

**Additional context**
- Software keyboards do not show an Enter key anymore when this setting is enabled.
- This problem might not only apply for AVD but for any hardware keyboard.

**Comment by Twometer** [comment]
This is because Skynet replaces the Enter button in the keyboard with a "Send" button. If the emulator does not map your enter key to this new key, like android does, then the Skynet App cannot fix this problem.
