### ISSUE TITLE
Dependencies on non-existing messages

### ISSUE THREAD

**Issue by daniel-lerch** [skynet-im/skynet-android#31]
**Describe the bug**
Most probably Skynet references temporary message IDs on edit or delete and does not change these dependencies before sending the message to the server.

**To Reproduce**
1. Open a chat in Skynet
2. Disconnect from the server
3. Write a message
4. Edit the message
5. Reconnect to the server
6. Enjoy getting kicked

**Expected behavior**
Skynet should edit the message content as long as the message has not been sent to the server.

**Smartphone**
 - Device: Samsung Galaxy S10+
 - OS: Android 10

**Additional context**
⚠️ Beware of concurrency issues when editing message contents while a send loop is running in the background.

**Comment by Twometer** [comment]
We can do it like whatsapp does it and not allow actions that require referencing the message ID (quoting for WhatsApp) while the message is not sent

**Comment by daniel-lerch** [comment]
> We can do it like whatsapp does it and not allow actions that require referencing the message ID (quoting for WhatsApp) while the message is not sent

That's the solution for lazy programmers 😂
But I agree that my proposal would be a lot of work for a small improvement.
